name: Flutter CD Android & IOS

on:
  push:
    branches:
    - main

jobs:
  Build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_11.3.app
    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    # Setup the flutter environment.
    - uses: subosito/flutter-action@v1
      with:
        channel: 'dev'

    # Get flutter dependencies.
    - run: flutter pub get

    - run: flutter build apk --debug

    - uses: actions/upload-artifact@v1
      with:
        name: debug-apk
        path: build/app/outputs/apk/debug/app-debug.apk

    - run: flutter build ios --release --no-codesig

    - uses: actions/upload-artifact@v1
      with:
        name: debug-ipa
        path: build/ios/iphoneos

